baseURL = "http://192.168.1.18:1313/"
languageCode = "ru"
title = "Сайт проекта"
theme = "PaperMod"

defaultContentLanguage = "ru"

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  homeInfoParams = { 
    Title = "Добро пожаловать!", 
    Content = "Сайт проекта по дисциплине «Проектная деятельность»"
  }

# Для корректного отображения постов из /journal/
mainSections = ["journal"]

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Главная"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "about"
  name = "О проекте"
  url = "/about/"
  weight = 2

  [[menu.main]]
  identifier = "participants"
  name = "Участники"
  url = "/participants/"
  weight = 3

  [[menu.main]]
  identifier = "journal"
  name = "Журнал"
  url = "/journal/"
  weight = 4

  [[menu.main]]
  identifier = "resources"
  name = "Ресурсы"
  url = "/resources/"
  weight = 5

